### ISSUE TITLE
ValueError: cannot reshape array of size 1205888 into shape (24)

### ISSUE THREAD

**Issue by Youssefa99** [jared-v-hoyt/des-image-encryption#1]
in cbc, ctr and ofb modes whenever I try to encrypt an image the following error occurs

**Comment by jared-v-hoyt** [comment]
Can you provide the image file and the command you used?

**Comment by jared-v-hoyt** [comment]
The issue dealt with how the tool handled padding when image sizes were not perfect 64-bit blocks and has now been resolved.
